// Copyright 2016 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.cloud.trace.util;

/**
 * A factory that generates identifiers.
 *
 * @param <T> the type of identifier generated by this factory.
 */
public interface IdFactory<T> {
  /**
   * Generates a new identifier.
   *
   * @return the new identifier.
   */
  T nextId();

  /**
   * Returns the invalid identifier value for {@code <T>}.
   *
   * @return the invalid identifier.
   */
  T invalid();
}
